# Generated by Django 2.2.4 on 2019-09-30 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarefa',
            old_name='data_espiracao',
            new_name='data_expiracao',
        ),
    ]
